resources:
  - url: http://127.0.0.1:5000/config-template-card.js
    type: module
views:
  - cards:
      - type: 'custom:config-template-card'
        variables:
          - states['light.bed_light'].state
          - states['cover.garage_door'].state
        entities:
          - light.bed_light
          - cover.garage_door
          - alarm_control_panel.ha_alarm
          - climate.ecobee
        card:
          type: "${vars[0] === 'on' ? 'custom:hui-glance-card' : 'custom:hui-entities-card'}"
          entities:
            - entity: alarm_control_panel.ha_alarm
              name: "${vars[1] === 'open' && states['alarm_control_panel.ha_alarm'].state === 'armed_home' ? 'Close the garage!' : ''}"
            - entity: binary_sensor.basement_floor_wet
            - entity: climate.ecobee
              name: "${states['climate.ecobee'].attributes.current_temperature > 22 ? 'Cozy' : 'Too Hot/Cold'}"
            - entity: cover.garage_door
            - entity: "${vars[0] === 'on' ? 'light.bed_light' : 'climate.ecobee'}"
              icon: "${vars[1] === 'open' ? 'mdi:hotel' : '' }"
